### ISSUE TITLE
`AppConfig::default` akan menyebabkan stack overflow jika file tidak wujud.

### ISSUE THREAD

**Issue by afiqzx** [samudradev/samudra-app#1]
`AppConfig::default` akan panggil `AppConfig::from_toml`. Tapi jika fail tidak wujud, `from_toml` akan ulang panggil `default` sehingga stack overflow.

Aku boleh betulkan tapi nak tahu apa penyelesaian yang baik. Sama ada:
- panic jika file tidak wujud buat masa ini.
- cipta lalai baharu. (cipta function baru dan set nilai yang perlu, dan pulangkan nilai tersebut)

Tapi untuk pilihan kedua, perlu bincang dulu nak letak nilai yang macam mana.

**Comment by afiqzx** [comment]
Ada perkara lain juga yang mahu ditanya, seperti 'macam mana format `databases.toml` yang sepatutnya?'

**Comment by Thaza-Kun** [comment]
Ok, faham dah apa yang berlaku. Aku dah buat silap panggilan berulang.
```rust
#[derive(Serialize, Deserialize, Debug)]
pub struct AppConfig {
    active: Mutex<String>,
    databases: Mutex<HashMap<String, DatabaseConfig>>,
}

impl AppConfig {
    pub fn from_toml(file: &Path) -> AppConfig {
        match file.exists() {
            true => {
                let contents = match fs::read_to_string(file) {
                    Ok(c) => c,
                    Err(e) => {
                        todo!("{}", e)
                    }
                };
                toml::from_str(&contents).unwrap()
            }
            // Sini panggil AppConfig::default() sedangkan fn ni dipanggil dari AppConfig::default()
            false => AppConfig::default(),
        }
    }
}

impl Default for AppConfig {
    fn default() -> Self {
        // Jika tiada fail, fn ni akan dipanggil berkali-kali
        AppConfig::from_toml(AppPaths::default().config_home.as_path())
    }
}
```

Terima kasih sebab perasan.

Fail `databases.toml` aku begini:
```toml
active = "nama_db_1"

[databases.nama_db_1]
path = '/path/to/nama_db_1/samudra.db'
engine = "sqlite" # <- dari struct database::DatabaseEngine

# kalau ada 2 db
[databases.nama_db_2]
path = '/path/to/nama_db_2/samudra.db'
engine = "sqlite"
```

Jadi boleh sediakan tetapan lalai berdasarkan struktur ini
